# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Format')),
            ],
        ),
    ]
