# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_auto_20170515_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colors', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=255, null=True, size=None)),
                ('type', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('power', models.CharField(max_length=255, null=True)),
                ('toughness', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardToToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.CardToken')),
            ],
        ),
    ]
