# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255, unique=True)),
                ('layout', models.CharField(max_length=255)),
                ('manaCost', models.CharField(max_length=255, null=True)),
                ('cmc', models.IntegerField()),
                ('colors', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=255, null=True, size=5)),
                ('type', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('power', models.CharField(max_length=255, null=True)),
                ('toughness', models.CharField(max_length=255, null=True)),
                ('loyalty', models.IntegerField(null=True)),
                ('reserved', models.BooleanField()),
                ('vintage', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=50, null=True, size=1)),
                ('legacy', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=50, null=True, size=1)),
                ('modern', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=50, null=True, size=1)),
                ('standard', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=50, null=True, size=1)),
                ('commander', django_mysql.models.SetCharField(models.CharField(max_length=50), max_length=50, null=True, size=1)),
            ],
        ),
    ]
