# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='loyalty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
